### ISSUE TITLE
Support 18.04

### ISSUE THREAD

**Issue by jamesbeedy** [elastisys/layer-charmscaler#2]

**Comment by simonklb** [comment]
Sorry for the delay! Bionic has been added as a valid series now.

I pushed a new revision of the charm as well and released it to the edge channel. I've verified it on the LXD provider with `juju deploy --channel edge --series bionic charmscaler`.

Let me know if you have any problems setting it up. Juju has been moving a lot since I last built the charm so it might be a bit outdated.
